#!/usr/bin/env python
# coding: utf-8

import re
import sys
import zipfile
import HTMLParser


def odcat(file_path):
    z = zipfile.ZipFile(file_path)
    content = z.open('content.xml')
    for line in content:
        for text in re.findall('(?<=>)[^<]+', line):
            yield text


if __name__ == '__main__':
    try:
        for line in odcat(sys.argv[1]):
            print HTMLParser.HTMLParser().unescape(line)
    except IOError:
        sys.stderr.write('File not found\n')
        sys.exit(1)
    except (KeyError, zipfile.BadZipfile) as e:
        sys.stderr.write('Not a valid od file. {}.\n'.format(e.message))
        sys.exit(1)
